name: rekam_medis_pasien
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/one.jpg
   - assets/images/two.jpg
   - assets/images/three.jpg
   - assets/images/four.jpg
   - assets/images/logo.png
